ISEF01_QuizApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('quiz.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
]

quiz/urls.py
from django.urls import path
from .views import KursHome
from .views import KursCreate
from .views import KursDetail
from .views import KursUpdate
from .views import KursDelete

from .views import FrageHome
from .views import FrageNichtFreigegeben
from .views import FrageCreate
from .views import FrageDetail
from .views import FrageUpdate
from .views import FrageDelete
from .views import RichtigOderFalschHome
from .views import RichtigOderFalschNichtFreigegeben
from .views import RichtigOderFalschCreate
from .views import RichtigOderFalschDetail
from .views import RichtigOderFalschUpdate
from .views import RichtigOderFalschDelete
from .views import ErgebnisHome
from .views import ErgebnisTopPunkte
from .views import ErgebnisTopGroupByPunkte
from .views import ErgebnisMCTopPunkte
from .views import ErgebnisTopMCGroupByPunkte
from .views import ErgebnisRFTopPunkte
from .views import ErgebnisTopRFGroupByPunkte
from .views import ErgebnisDetail
from .views import index
from .views import MCTestSelect
from .views import RFTestSelect
from .views import MeldungMCFrageSelect
from .views import MeldungRFFrageSelect
from .views import MCTestStart
from .views import RFTestStart
from .views import LadeMCFragen
from .views import LadeRFFragen
from .views import MeldungMCFragenHome
from .views import MeldungMCFragenDetail
from .views import MeldungMCFragenUpdate
from .views import MeldungMCFragenDelete
from .views import MeldungMCFragenUpdateNichtGelesen
from .views import MeldungRFFragenHome
from .views import MeldungRFFragenDetail
from .views import MeldungRFFragenUpdate
from .views import MeldungRFFragenDelete
from .views import MeldungRFFragenUpdateNichtGelesen


urlpatterns = [
	 path('', index, name='index'),
     path('kurs', KursHome.as_view(), name='kurs_start'),
	 path('frage', FrageHome.as_view(), name='frage_start'),
	 path('frage/nichtfreigegeben', FrageNichtFreigegeben.as_view(), name='frage_nichtfreigegeben'),
     path('richtigoderfalsch', RichtigOderFalschHome.as_view(), name='richtigoderfalsch_start'),
     path('richtigoderfalsch/nichtfreigegeben', RichtigOderFalschNichtFreigegeben.as_view(), name='richtigoderfalsch_nichtfreigegeben'),
     path('ergebnis', ErgebnisHome.as_view(), name='ergebnis_start'),
     path('ergebnistoppunkte', ErgebnisTopPunkte.as_view(), name='ergebnis_toppunkte'),
     path('ergebnistopgroupbypunkte', ErgebnisTopGroupByPunkte.as_view(), name='ergebnis_topgroupbypunkte'),
     path('ergebnismctoppunkte', ErgebnisMCTopPunkte.as_view(), name='ergebnis_mctoppunkte'),
     path('ergebnistopmcgroupbypunkte', ErgebnisTopMCGroupByPunkte.as_view(), name='ergebnis_topmcgroupbypunkte'),
     path('ergebnisrftoppunkte', ErgebnisRFTopPunkte.as_view(), name='ergebnis_rftoppunkte'),
     path('ergebnistoprfgroupbypunkte', ErgebnisTopRFGroupByPunkte.as_view(), name='ergebnis_toprfgroupbypunkte'),	 
	 path('mctest', MCTestSelect, name='mctest_select'),
     path('rftest', RFTestSelect, name='rftest_select'),
	 path('mctest/<arg1>', MCTestStart, name='mctest_start'),
	 path('mctest/<arg1>/<arg2>', MCTestStart, name='mctest_start'),
     path('rftest/<arg1>', RFTestStart, name='rftest_start'),
     path('rftest/<arg1>/<arg2>', RFTestStart, name='rftest_start'),
	 path('kurs/neu/', KursCreate.as_view(), name='neuer_kurs'),
	 path('frage/neu/', FrageCreate.as_view(), name='neue_frage'),
     path('richtigoderfalsch/neu/', RichtigOderFalschCreate.as_view(), name='richtigoderfalsch_neue_frage'),
	 path('kurs/<int:pk>/', KursDetail.as_view(), name='kurs_detail'),
	 path('frage/<int:pk>/', FrageDetail.as_view(), name='frage_detail'),
     path('richtigoderfalsch/<int:pk>/', RichtigOderFalschDetail.as_view(), name='richtigoderfalsch_detail'),
     path('ergebnis/<int:pk>/', ErgebnisDetail.as_view(), name='ergebnis_detail'),
	 path('kurs/<int:pk>/update/', KursUpdate.as_view(), name='kurs_update'),
	 path('frage/<int:pk>/update/', FrageUpdate.as_view(), name='frage_update'),
     path('richtigoderfalsch/<int:pk>/update/', RichtigOderFalschUpdate.as_view(), name='richtigoderfalsch_update'),
	 path('kurs/<int:pk>/delete/', KursDelete.as_view(), name='kurs_delete'),
	 path('frage/<int:pk>/delete/', FrageDelete.as_view(), name='frage_delete'),
     path('richtigoderfalsch/<int:pk>/delete/', RichtigOderFalschDelete.as_view(), name='richtigoderfalsch_delete'),
     path('ajax/lade-mcfragen/', LadeMCFragen, name='ajax_lade_mcfragen'), 
     path('ajax/lade-rffragen/', LadeRFFragen, name='ajax_lade_rffragen'), 
     path('meldungmcfrage', MeldungMCFrageSelect, name='meldungmcfrage_select'),
	 path('meldungmcfragen', MeldungMCFragenHome.as_view(), name='meldungmcfragen'),
	 path('meldungmcfragenungelesen', MeldungMCFragenUpdateNichtGelesen.as_view(), name='meldungmcfragen_ungelesen'),
     path('meldungmcfragen/<int:pk>/', MeldungMCFragenDetail.as_view(), name='meldungmcfragen_detail'),
	 path('meldungmcfragen/<int:pk>/update/', MeldungMCFragenUpdate.as_view(), name='meldungmcfragen_update'),
	 path('meldungmcfragen/<int:pk>/delete/', MeldungMCFragenDelete.as_view(), name='meldungmcfragen_delete'),
     path('meldungrffrage', MeldungRFFrageSelect, name='meldungrffrage_select'),
	 path('meldungrffragen', MeldungRFFragenHome.as_view(), name='meldungrffragen'),
     path('meldungrffragen/<int:pk>/', MeldungRFFragenDetail.as_view(), name='meldungrffragen_detail'),
	 path('meldungrffragen/<int:pk>/update/', MeldungRFFragenUpdate.as_view(), name='meldungrffragen_update'),
	 path('meldungrffragen/<int:pk>/delete/', MeldungRFFragenDelete.as_view(), name='meldungrffragen_delete'),
	 path('meldungrffragenungelesen', MeldungRFFragenUpdateNichtGelesen.as_view(), name='meldungrffragen_ungelesen'),
]

quiz/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Kurs(models.Model):
    name = models.CharField(max_length=50,help_text='Geben Sie den Namen des Kurses ein')
    beschreibung = models.CharField(max_length=255,help_text='Geben Sie die Beschreibung des Kurses ein')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('kurs_detail', args=[str(self.id)])

class Frage(models.Model):
    name = models.CharField(max_length=255,blank=False,help_text='Geben Sie hier die Frage ein')
    kurs = models.ForeignKey(Kurs,null=True,blank=False,on_delete=models.CASCADE,help_text='Wählen Sie den Kurs, welchem die Frage zugewiesen wird')
    antwort1 = models.CharField(max_length=255,blank=False,null=True,help_text='Geben Sie die Antwort1 der Frage ein')
    antwort1richtig = models.BooleanField(default=False,help_text='Geben Sie an ob Antwort1 richtig ist',verbose_name="Antwort1 richtig?")
    antwort2 = models.CharField(max_length=255,blank=False,null=True,help_text='Geben Sie die Antwort2 der Frage ein')
    antwort2richtig = models.BooleanField(default=False,help_text='Geben Sie an ob Antwort2 richtig ist',verbose_name="Antwort2 richtig?")
    antwort3 = models.CharField(max_length=255,blank=True,null=True,help_text='Geben Sie die Antwort3 der Frage ein (optional)')
    antwort3richtig = models.BooleanField(default=False,help_text='Geben Sie an ob Antwort3 richtig ist',verbose_name="Antwort3 richtig?")
    antwort4 = models.CharField(max_length=255,blank=True,null=True,help_text='Geben Sie die Antwort4 der Frage ein (optional)')
    antwort4richtig = models.BooleanField(default=False,help_text='Geben Sie an ob Antwort4 richtig ist',verbose_name="Antwort4 richtig?")
    freigegeben=models.BooleanField(default=False,help_text='Frage freigeben?',verbose_name="Frage freigeben")
	
    def __str__(self):
        return self.name
		
    def get_absolute_url(self):
        return reverse('frage_detail', args=[str(self.id)])

class RichtigOderFalsch(models.Model):
    name = models.CharField(max_length=255,blank=False,help_text='Geben Sie hier die Frage ein')
    kurs = models.ForeignKey(Kurs,null=True,blank=False,on_delete=models.CASCADE,help_text='Wählen Sie den Kurs, welchem die Frage zugewiesen wird')
    behauptungrichtig = models.BooleanField(default=False,verbose_name="Behauptung wahr?")
    freigegeben=models.BooleanField(default=False,help_text='Frage freigeben?',verbose_name="Frage freigeben")
	
    def __str__(self):
        return self.name
		
    def get_absolute_url(self):
        return reverse('richtigoderfalsch_detail', args=[str(self.id)])

class Ergebnis(models.Model):
    testmodus = models.CharField(max_length=20,blank=False)
    benutzername = models.CharField(max_length=50,blank=False)
    kursid = models.CharField(max_length=5,blank=False)
    kursname = models.CharField(max_length=50,blank=False)
    zeitsekunden = models.IntegerField(blank=False)
    datum = models.DateField(auto_now_add=True)
    punkte = models.IntegerField(blank=False)
    fragentotal = models.IntegerField(blank=False)
    fragenkorrekt = models.IntegerField(blank=False)
    fragenfalsch = models.IntegerField(blank=False)
	
    def __str__(self):
        return self.benutzername
		
    def get_absolute_url(self):
        return reverse('ergebnis_detail', args=[str(self.id)])
		
class MeldungMCFragen(models.Model):

    kursname = models.CharField(max_length=50,blank=False)
    kursid = models.ForeignKey(Kurs,null=True,blank=False,on_delete=models.CASCADE)
    frageid = models.ForeignKey(Frage,null=True,blank=False,on_delete=models.CASCADE)
    frage = models.CharField(max_length=255,blank=False)
    nachricht = models.CharField(max_length=500,blank=False)
    benutzername = models.CharField(max_length=50,blank=False)
    gelesen=models.BooleanField(default=False)
	
    def __str__(self):
        return self.frage
		
    def get_absolute_url(self):
        return reverse('meldungmcfragen_detail', args=[str(self.id)])

	
class MeldungRFFragen(models.Model):

    kursname = models.CharField(max_length=50,blank=False)
    kursid = models.ForeignKey(Kurs,null=True,blank=False,on_delete=models.CASCADE)
    frageid = models.ForeignKey(RichtigOderFalsch,null=True,blank=False,on_delete=models.CASCADE)
    frage = models.CharField(max_length=255,blank=False)
    nachricht = models.CharField(max_length=500,blank=False)
    benutzername = models.CharField(max_length=50,blank=False)
    gelesen=models.BooleanField(default=False)
	
    def __str__(self):
        return self.frage
		
    def get_absolute_url(self):
        return reverse('meldungrffragen_detail', args=[str(self.id)])

quiz/forms.py
from django import forms
from .models import Kurs, Frage, RichtigOderFalsch

COUNT_CHOICE= [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('10', '10'),
    ('15', '15'),
    ('20', '20')
    ]

class TestSelectForm(forms.Form):
    kurs = forms.ModelChoiceField(queryset=Kurs.objects.all(),required=True)
    questioncount = forms.IntegerField(label='Wähle die maximale Anzahl der Fragen?', widget=forms.Select(choices=COUNT_CHOICE))
	
class MeldungMCFrageForm(forms.Form):
    kurs = forms.ModelChoiceField(queryset=Kurs.objects.all(),required=True)								 
    frage = forms.ModelChoiceField(queryset=Frage.objects.all(),required=True)
    nachricht = forms.CharField(max_length=500, required=True, widget=forms.Textarea(attrs={"rows":5, "cols":100}))

	
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['frage'].queryset = Frage.objects.none()
        if 'kurs' in self.data:
            try:
                kurs_id = int(self.data.get('kurs'))
                self.fields['frage'].queryset = Frage.objects.filter(kurs=kurs_id, freigegeben = True).order_by('name')
            except (ValueError, TypeError):
                pass 

class MeldungRFFrageForm(forms.Form):
    kurs = forms.ModelChoiceField(queryset=Kurs.objects.all(),required=True)								 
    frage = forms.ModelChoiceField(queryset=RichtigOderFalsch.objects.all(),required=True)
    nachricht = forms.CharField(max_length=500, required=True, widget=forms.Textarea(attrs={"rows":5, "cols":100}))

	
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['frage'].queryset = RichtigOderFalsch.objects.none()
        if 'kurs' in self.data:
            try:
                kurs_id = int(self.data.get('kurs'))
                self.fields['frage'].queryset = RichtigOderFalsch.objects.filter(kurs=kurs_id, freigegeben = True).order_by('name')
            except (ValueError, TypeError):
                pass 

quiz/templates/meldungrffrage/meldungrffrage.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-md-center">
		<div class="col-sm-4 ">
        {% include 'messages.html' %}
	<h2>RF-Frage melden</h2>
  <form method="post" id="kursForm" data-kurs-url="{% url 'ajax_lade_rffragen' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button class="btn btn-success btn-sm" type="submit">Speichern</button>
    <a class="btn btn-danger btn-sm" href="{% url 'index' %}">Abbrechen</a>
  </form>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script>
    $("#id_kurs").change(function () {
      var url = $("#kursForm").attr("data-kurs-url");  
      var kursId = $(this).val(); 

      $.ajax({                     
        url: url,                   
        data: {
          'kurs': kursId    
        },
        success: function (data) { 
          $("#id_frage").html(data);  
        }
      });

    });
  </script>
{% endblock content %}

quiz/templates/meldungrffrage/meldungrffrage_dropdownlist.html
<option value="">---------</option>
{% for frage in fragen %}
<option value="{{ frage.pk }}">{{ frage.name }}</option>
{% endfor %}

quiz/templates/meldungrffrage/meldungrffragen_delete.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center">Meldung RF-Frage löschen</h2>
<div class="container ">
    <div class="row justify-content-md-center">
		<div class="col-sm-6">
            <form action="" method="post">{% csrf_token %}
                <p>Bist du sicher das du diese Meldung RF-Frage löschen willst?</p>
                <p><strong>{{ meldungrffragen.frage }} - {{ meldungrffragen.benutzername }} - {{ meldungrffragen.nachricht }}</strong></p>
                <a class="btn btn-secondary btn-sm" href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">Zurück</a>
                <button type="submit btn-sm" class="btn btn-danger btn-sm">Löschen</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

quiz/templates/meldungrffrage/meldungrffragen_detail.html
{% extends 'base.html' %}

{% block content %}
{% include 'messages.html' %}
<div class="container">
    <div class="row justify-content-md-center">
		<div class="col-sm-7 ">
			<h2 class="text-center">Meldung RF-Frage Details</h2>
            <table class="table table-sm table-striped" border="3px">
    		<tr><td width=50%>Kursname:</td><td class="text-center">{{meldungrffragen.kursname}}</td></tr>
			<tr><td> Kursid:</td><td class="text-center"> {{meldungrffragen.kursid }}</td></tr>
    		<tr><td> Frageid:</td><td class="text-center"> {{meldungrffragen.frageid }}</td></tr>
			<tr><td> Frage:</td><td class="text-center"> {{meldungrffragen.frage }}</td></tr>
			<tr><td> Nachricht:</td><td class="text-center"> {{meldungrffragen.nachricht }}</td></tr>
			<tr><td> Benutzername:</td><td class="text-center"> {{meldungrffragen.benutzername }}</td></tr>
			<tr><td> Gelesen:</td><td class="text-center"> {{meldungrffragen.gelesen }}</td></tr>

			</table>
    		<a class="btn btn-secondary btn-sm" href="{% url 'meldungrffragen' %}">Zurück</a>
			<a class="btn btn-danger btn-sm" href="{% url 'meldungrffragen_delete' meldungrffragen.pk %}">Löschen</a>
    		<a class="btn btn-success btn-sm" href="{% url 'meldungrffragen_update' meldungrffragen.pk %}">Bearbeiten</a>

		</div>
    </div>
</div>

{% endblock content %}

quiz/templates/meldungrffrage/meldungrffragen_home.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
	<p><button type="button" class="btn btn-outline-secondary" onclick="location.href='{% url 'meldungrffrage_select'  %}'"> RF-Fragen melden</button></p>
</div>

<h2 class="text-center">Alle gemeldeten RF-Fragen</h2>

<div class="container text-center">
	<div class="row justify-content-md-center">
		<div class="col-sm-8 ">
			<table  class ="table border table-hover table-striped">
				<thead class="table-dark">
					<th width=100 scope = "col">Kursname</th>
					<th width=100 scope = "col">Kursid</th>
					<th width=100 scope = "col">Frageid</th>
					<th width=100 scope = "col">Frage</th>
					<th width=100 scope = "col">Nachricht</th>
					<th width=550 scope = "col">Benutzername</th>
					<th width=550 scope = "col">Gelesen</th>
				</thead>

				<tbody>
				{% for meldungrffragen in object_list %}
					<tr>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.kursname }}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.kursid }}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.frageid }}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.frage}}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.nachricht}}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.benutzername}}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.gelesen}}</a> </td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>


{% endblock content %}

quiz/templates/meldungrffrage/meldungrffragen_unread.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
	<p><button type="button" class="btn btn-outline-secondary" onclick="location.href='{% url 'meldungrffrage_select'  %}'"> Rf-Fragen melden</button></p>
</div>

<h2 class="text-center">Nicht gelesene gemeldete RF-Fragen</h2>

<div class="container text-center">
	<div class="row justify-content-md-center">
		<div class="col-sm-8 ">
			<table  class ="table border table-hover table-striped">
				<thead class="table-dark">
					<th width=100 scope = "col">Kursname</th>
					<th width=100 scope = "col">Kursid</th>
					<th width=100 scope = "col">Frageid</th>
					<th width=100 scope = "col">Frage</th>
					<th width=100 scope = "col">Nachricht</th>
					<th width=550 scope = "col">Benutzername</th>
					<th width=550 scope = "col">Gelesen</th>
				</thead>

				<tbody>
				{% for meldungrffragen in object_list %}
					<tr>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.kursname }}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.kursid }}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.frageid }}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.frage}}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.nachricht}}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.benutzername}}</a> </td>
						<td> <a href="{% url 'meldungrffragen_detail' meldungrffragen.pk %}">{{ meldungrffragen.gelesen}}</a> </td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>


{% endblock content %}

quiz/templates/meldungrffrage/meldungrffragen_update.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center">Meldung RF-Frage bearbeiten</h2>
<div class="container">
    <div class="row justify-content-md-center">
		<div class="col-lg-7">
            <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
                <a class="btn btn-danger btn-sm" href="{% url 'meldungrffragen' %}">Abbrechen</a>
                <button type="reset" class="btn btn-secondary btn-sm">Zurücksetzen</button>
                <button type="submit" class="btn btn-success btn-sm">Speichern</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}